config/routes.rb
Timely::Application.routes.draw do
  root :to => 'tweets#index', :as => :root

  match "auth/twitter/callback" => "sessions#create"
  match "auth/failure" => "sessions#error"
  match "signout" => "sessions#destroy", :as => :signout
  match "settings" => "users#edit", :as => :settings
  match "tweets/shorten" => "tweets#shorten", :as => :shorten_link
  match "archive" => "tweets#archive", :as => :archive

  resources :tweets, :users
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user

  scope :pending, where(:status => 'pending').order(:scheduled_date)
  scope :archived, where("status != 'pending'").order("sent_date DESC")
  scope :overdue, lambda { where("scheduled_date < ? AND status='pending'", Time.now.utc) }
  scope :sent, where(:status => 'sent')
  scope :imported, where(:status => 'imported')

  self.per_page = 10

  def self.send_overdue_tweets
    Tweet.overdue.includes(&:user).each do |tweet|
      tweet.issue_tweet
    end
  end

  def self.update_stats(since = nil)
    if since
      tweets = Tweet.where('sent_date > ?', since)
    else
      tweets = Tweet
    end

    tweets.sent.includes(:user).group_by(&:user).each do |user, tweets|
      if user.bitly_username && user.bitly_api_key
        begin
          bitly = Bitly.new(user.bitly_username, user.bitly_api_key)
        rescue
        else
          short_urls = tweets.map(&:short_url).compact.select {|t| t.size > 0}

          # Bitly API takes up to 15 at a time
          short_urls.in_groups_of(15) do |urls|
            response = bitly.info(urls.compact)

            unless defined?(response.error)
              [response].flatten.each do |result|
                Tweet.update_all({ :user_clicks => result.user_clicks, :global_clicks => result.global_clicks }, :short_url => result.short_url)
              end
            end
          end
        end
      end
    end
  end
  
  def issue_tweet
    log = Logger.new("#{Rails.root}/log/tweets.log")

    if user
      Twitter.configure do |config|
        config.consumer_key = TWITTER_KEY
        config.consumer_secret = TWITTER_SECRET
        config.oauth_token = user.twitter_token
        config.oauth_token_secret = user.twitter_secret
      end

      begin
        client = Twitter::Client.new
        response = client.update(message)
      rescue Exception => e
        # TODO: Retry a certain number of times
        $boxcar.notify(user.email_address, "Problem sending #{user.twitter_handle} tweet '#{message}'.")
        log.error "[#{Time.now}] Unable to send tweet ID ##{id} for #{user.twitter_handle}: #{e.message}"
        update_attributes({ :status => 'error', :error => e.message })
      else
        $boxcar.notify(user.email_address, "Successfully sent #{user.twitter_handle} tweet '#{message}'.")
        log.info "[#{Time.now}] Successfully sent tweet ID ##{id} for #{user.twitter_handle}"
        update_attributes({ :status => 'sent', :tweet_uid => response.id.to_i, :sent_date => Time.now })
      end
    else
      log.error "[#{Time.now}] Invalid user ID ##{user_id} for tweet ID ##{id}"
      update_attribute(:status, 'error')
    end    
  end
end

app/controllers/tweets_controller.rb
require 'uri'
require 'open-uri'

class TweetsController < ApplicationController
  before_filter :set_timezone
  respond_to :json, :only => [ :shorten ]
  
  def index
    @tweet = Tweet.new
    if params[:url]
      (title, short_url) = shorten_url params[:url]
      
      @tweet.long_url = params[:url]
      @tweet.short_url = short_url
      @tweet.message = "#{title} #{short_url}"
    end

    package_data
  end

  def create
    if current_user
      Time.zone = current_user.time_zone

      if tweet = current_user.tweets.create(params[:tweet])      
        if params[:commit] == 'Send Now'
          tweet.update_attribute(:scheduled_date, nil)
          tweet.issue_tweet
          redirect_to root_path, :notice => "New tweet has been sent."
        else
          redirect_to root_path, :notice => "New tweet scheduled."
        end
      else
        redirect_to root_path, :alert => "Error adding new tweet."
      end
    else
      redirect_to root_path, :alert => "You must be logged in via Twitter for that."
    end
  end

  def edit
    @tweet = Tweet.find(params[:id])
    package_data
    render 'index'
  end

  def update
    @tweet = Tweet.find(params[:id])
    
    if @tweet.update_attributes(params[:tweet])
      if params[:commit] == 'Send Now'
        tweet.issue_tweet
        redirect_to root_path, :notice => "New tweet has been sent."
      else
        redirect_to root_path, :notice => "New tweet scheduled."
      end
    else
      redirect_to root_path, :alert => 'Problem updating this tweet.'
    end
  end

  def destroy
    Tweet.find(params[:id]).destroy
    redirect_to root_path
  end

  def shorten
    if current_user.bitly_username && current_user.bitly_username.size > 0 && 
       current_user.bitly_api_key && current_user.bitly_api_key.size > 0
      begin
        (title, short_url, long_url) = shorten_url params[:url]
      rescue
        error = "Unable to shorten URL."
      end
    else
      error = "Bit.ly not configured. Visit settings to enable."
    end

    respond_with do |format|
      if error
        format.json { render :json => { :error => error } }
      else
        format.json { render :json => { :title => title, :short_url => short_url, :long_url => long_url }.to_json }
      end
    end
  end
  
  def archive
    if current_user
      @archived_tweets = current_user.tweets.archived.page(params[:page])
    else
      redirect_to root_path, :alert => "You must be logged in for that."
    end
  end

  private

  def package_data
    if current_user
      @upcoming_tweets = current_user.tweets.pending

      if @upcoming_tweets.empty?
        d = Date.today + (Time.now.hour > current_user.quick_pick_start ? 1 : 0).days
        t = Time.new(d.year, d.month, d.day, current_user.quick_pick_start, 0)
      else
        t = @upcoming_tweets.last.scheduled_date + current_user.quick_pick_interval.minutes
      end

      @quickpick = t.strftime("%Y-%m-%d %I:%M%p")
    end
  end

  def shorten_url(url)
    url.insert(0, 'http://') unless (url.starts_with?('http://') || url.starts_with?('https://'))

    # Remove Google Adwords gunk
    (base_url, querystring) = url.split('?')
    if querystring
      querystring = querystring.split('&').select {|arg| !arg.index('utm_')}.join('&')
      url = (querystring.size > 0) ? "#{base_url}?#{querystring}" : base_url
    end

    doc = Nokogiri::HTML(open(url))
    title = doc.at_css("title").inner_html
    
    bitly = Bitly.new(current_user.bitly_username, current_user.bitly_api_key)
    short_url = bitly.shorten(URI.encode(url)).short_url

    [title, short_url, url]
  end
  
  def set_timezone
    Time.zone = current_user.time_zone if current_user && current_user.time_zone
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_for @tweet do |f| %>
  <p>
    <%= f.label :long_url, "URL" %><br>
    <%= f.text_field :long_url %>
    <%= content_tag :button, "shorten", :class => 'shorten', :type => 'button' %> <%= image_tag "spinner.gif", :id => "spinner"%><br>
    <span id="shortenerr"></span>
  </p>

  <p>
    <%= f.label :message, "Tweet" %><br>
    <%= f.text_area :message, :size => '50x3' %><br>
    <span id="charcount">140 characters left</span>
  </p>

  <p>
    <%= f.label :scheduled_date, "Scheduled Date" %><br>
    <%= f.text_field :scheduled_date %>
    <%= content_tag :button, "quick pick", :class => 'quickpick', :type => 'button', "data-timestamp" => @quickpick %>
  </p>

  <%= f.hidden_field :short_url %>

  <%= primary_button_submit_tag "Schedule Tweet" %>
  <%= button_submit_tag "Send Now" %>
  <%= button_submit_tag("Reset Form", { :name => 'reset', :id => 'reset_button', :type => "reset" }) %>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="tweet">
  <div class="message"><%= raw Rinku.auto_link tweet.message %></div>
  <% if tweet.long_url && tweet.long_url.size > 0 %>
    <div class="long_url">Link: <%= raw Rinku.auto_link(tweet.long_url) %></div>
  <% end %>
  <div class="tweet_options">
    <% if tweet.status == 'pending' %>
      <%= raw "Scheduled for #{tweet.scheduled_date.strftime("%m/%d/%y %I:%M%P")} &middot; " if tweet.scheduled_date %>
      <%= link_to "edit", edit_tweet_path(tweet) %> &middot;
      <%= link_to "delete", tweet, :confirm => "Delete the tweet '#{tweet.message}'?", :method => :delete %>
    <% elsif tweet.status == 'sent' %>
      Status: <span class="status_sent"><%= link_to "sent", "https://twitter.com/#!/#{tweet.user.twitter_handle}/status/#{tweet.tweet_uid}" %></span>. Clicks: <%= "#{tweet.user_clicks.to_i}/#{tweet.global_clicks.to_i}." %>
    <% else %>
      Status: <span class="status_<%= tweet.status %>" <%= " title='#{tweet.error}'" if tweet.error %>><%= tweet.status %></span>.
    <% end %>
    <%= tweet.sent_date.strftime(" (%m/%d/%y %I:%M%P)") if tweet.sent_date %>
  </div>
</div>

app/views/tweets/archive.html.erb
<h3>Archived tweets</h3>
<% if @archived_tweets.size > 0 %>
  <%= will_paginate @archived_tweets, :previous_label => '&#8592; Newer', :next_label => 'Older &#8594;' %>
  <div id="tweets">
    <%= render @archived_tweets %>
  </div>
  <%= will_paginate @archived_tweets, :previous_label => '&#8592; Newer', :next_label => 'Older &#8594;' %>
<% else %>
  None yet. Schedule some tweets and they'll appear here after they've been sent.
<% end %>

app/views/tweets/index.html.erb
<% if current_user %>
  <h3>Schedule a new tweet</h3>

  <%= render :partial => 'form' %>

  <h3>Pending tweets</h3>

  <% if @upcoming_tweets.empty? %>
    No upcoming tweets currently scheduled.
  <% else %>
    <div id="tweets">
      <%= render @upcoming_tweets %>
    </div>
  <% end %>
<% else %>
  <h3>Oh hello!</h3>
  <p><%= APP_NAME %> lets you schedule tweets to be sent out at a future point in time via an easy bookmarklet with auto-login and link shortener support. <a href="auth/twitter">Connect</a> via your Twitter account to get started.</p>
  <p>This app is primarily being developed for my curated <a href="http://twitter.com/martiansoil">Martian Soil</a> Twitter account and learn more about Ruby on Rails, but anyone else is welcome to try it out. Drop me (Joost Schuur) <a href="mailto:jschuur@jschuur.com">a line</a> and let me know what you think if you use it..</p>
<% end %>