config/routes.rb
Timely::Application.routes.draw do
  root :to => 'tweets#index', :as => :root

  match "auth/twitter/callback" => "sessions#create"
  match "auth/failure" => "sessions#error"
  match "signout" => "sessions#destroy", :as => :signout
  match "settings" => "users#edit", :as => :settings
  match "tweets/shorten" => "tweets#shorten", :as => :shorten_link
  match "archive" => "tweets#archive", :as => :archive

  resources :tweets, :users
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= APP_NAME %></title>
    <%= stylesheet_link_tag "application", "jquery-ui", "timepicker" %>
    <link href='http://fonts.googleapis.com/css?family=Droid+Sans:400,700|Varela|Aclonica' rel='stylesheet' type='text/css'>
    <%= javascript_include_tag "application", "timepicker" %>
    <%= javascript_include_tag params[:controller] if CONTROLLER_SPECIFIC_JAVASCRIPT.include?(params[:controller]) %>
    <%= csrf_meta_tag %>
    <!--[if !IE 7]>
    	<style type="text/css">
    		#wrap {display:table;height:100%}
    	</style>
    <![endif]-->
    <%= yield(:head) %>
  </head>
  <body>
    <div id="wrap">
      <div id="header">
        <div id="brand"><%= content_tag :h1, link_to(APP_NAME, root_path) %></div>
        <ul id="nav">
          <% if current_user %>
            <li><%= content_tag :span, link_to("@#{current_user.twitter_handle}", "http://twitter.com/#{current_user.twitter_handle}"), :class => 'navopt' %></li>
            <li><%= content_tag :span, link_to("Archive", archive_path), :class => 'navopt' %></li>
            <li><%= content_tag :span, link_to("Settings", settings_path), :class => 'navopt' %></li>
            <li><%= content_tag :span, link_to("Log out", signout_path), :class => 'navopt' %></li>
          <% else %>
            <li> <%= content_tag :span, link_to("Connect via Twitter", root_path + 'auth/twitter'), :class => 'navopt' %></li>
          <% end %>
        </ul>
      </div>

      <div id="main">
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        <% end %>
        <%= content_tag :h3, yield(:title) if show_title? %>
        <%= yield %>
      </div>
    </div>
    <div id="footer">
      Built by <a href="http://twitter.com/joostschuur">@jooostschuur</a> (<a href="https://trello.com/board/timely/512e1ff53ef3764859003066">todo list</a>/<a href="http://github.com/jschuur/timely">source</a>).
    </div>
  </body>
</html>